export const WS_FEED_CONNECTION_START = 'WS_FEED_CONNECTION_START';
export const WS_FEED_CONNECTION_SUCCESS = 'WS_FEED_CONNECTION_SUCCESS';
export const WS_FEED_CONNECTION_ERROR = 'WS_FEED_CONNECTION_ERROR';
export const WS_FEED_CONNECTION_CLOSED = 'WS_FEED_CONNECTION_CLOSED';
export const WS_FEED_GET_ORDER_MESSAGE = 'WS_FEED_GET_ORDER_MESSAGE';
export const WS_FEED_CONNECTION_CLOSE = 'WS_FEED_CONNECTION_CLOSE';

export const wsFeedActions = {
    wsInit: WS_FEED_CONNECTION_START,
    wsClose: WS_FEED_CONNECTION_CLOSE,
    onMessage: WS_FEED_GET_ORDER_MESSAGE,
    onOpen: WS_FEED_CONNECTION_SUCCESS,
    onClose: WS_FEED_CONNECTION_CLOSED,
    onError: WS_FEED_CONNECTION_ERROR
}


export const WS_ORDER_CONNECTION_START = 'WS_ORDER_CONNECTION_START';
export const WS_ORDER_CONNECTION_SUCCESS = 'WS_ORDER_CONNECTION_SUCCESS';
export const WS_ORDER_CONNECTION_ERROR = 'WS_ORDER_CONNECTION_ERROR';
export const WS_ORDER_CONNECTION_CLOSED = 'WS_ORDER_CONNECTION_CLOSED';
export const WS_ORDER_GET_ORDER_MESSAGE = 'WS_ORDER_GET_ORDER_MESSAGE';
export const WS_ORDER_CONNECTION_CLOSE = 'WS_ORDER_CONNECTION_CLOSE';

export const wsOrderActions = {
    wsInit: WS_ORDER_CONNECTION_START,
    wsClose: WS_ORDER_CONNECTION_CLOSE,
    onMessage: WS_ORDER_GET_ORDER_MESSAGE,
    onOpen: WS_ORDER_CONNECTION_SUCCESS,
    onClose: WS_ORDER_CONNECTION_CLOSED,
    onError: WS_ORDER_CONNECTION_ERROR


}
